version: "3"
services:
  grpc-devbox:
    init: true
    container_name: grpc-devbox
    # Note that the path of the Dockerfile and context is relative to the *primary*
    # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
    # array). The sample below assumes your primary file is in the root of your project.
    build:
      context: ../
      dockerfile: ./.devcontainer/Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - grpc-monorepo:/grpc-monorepo
      - ~/.ssh/id_rsa:/home/dev-user/.ssh/id_rsa:ro
      - ~/.ssh/id_ed25519:/home/dev-user/.ssh/id_ed25519:ro
    ports:
      - 12345:80

volumes:
  grpc-monorepo: {}
